/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './pages/__root'
import { Route as DefaultLayoutImport } from './pages/_defaultLayout'
import { Route as DefaultLayoutIndexImport } from './pages/_defaultLayout/index'
import { Route as DefaultLayoutTravelImport } from './pages/_defaultLayout/travel'
import { Route as DefaultLayoutLedgerImport } from './pages/_defaultLayout/ledger'
import { Route as DefaultLayoutInvestmentImport } from './pages/_defaultLayout/investment'
import { Route as DefaultLayoutBlogImport } from './pages/_defaultLayout/blog'
import { Route as DefaultLayoutAuthSignupImport } from './pages/_defaultLayout/auth/signup'
import { Route as DefaultLayoutAuthLoginImport } from './pages/_defaultLayout/auth/login'

// Create/Update Routes

const DefaultLayoutRoute = DefaultLayoutImport.update({
  id: '/_defaultLayout',
  getParentRoute: () => rootRoute,
} as any)

const DefaultLayoutIndexRoute = DefaultLayoutIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DefaultLayoutRoute,
} as any)

const DefaultLayoutTravelRoute = DefaultLayoutTravelImport.update({
  id: '/travel',
  path: '/travel',
  getParentRoute: () => DefaultLayoutRoute,
} as any)

const DefaultLayoutLedgerRoute = DefaultLayoutLedgerImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => DefaultLayoutRoute,
} as any)

const DefaultLayoutInvestmentRoute = DefaultLayoutInvestmentImport.update({
  id: '/investment',
  path: '/investment',
  getParentRoute: () => DefaultLayoutRoute,
} as any)

const DefaultLayoutBlogRoute = DefaultLayoutBlogImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => DefaultLayoutRoute,
} as any)

const DefaultLayoutAuthSignupRoute = DefaultLayoutAuthSignupImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => DefaultLayoutRoute,
} as any)

const DefaultLayoutAuthLoginRoute = DefaultLayoutAuthLoginImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => DefaultLayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_defaultLayout': {
      id: '/_defaultLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof DefaultLayoutImport
      parentRoute: typeof rootRoute
    }
    '/_defaultLayout/blog': {
      id: '/_defaultLayout/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof DefaultLayoutBlogImport
      parentRoute: typeof DefaultLayoutImport
    }
    '/_defaultLayout/investment': {
      id: '/_defaultLayout/investment'
      path: '/investment'
      fullPath: '/investment'
      preLoaderRoute: typeof DefaultLayoutInvestmentImport
      parentRoute: typeof DefaultLayoutImport
    }
    '/_defaultLayout/ledger': {
      id: '/_defaultLayout/ledger'
      path: '/ledger'
      fullPath: '/ledger'
      preLoaderRoute: typeof DefaultLayoutLedgerImport
      parentRoute: typeof DefaultLayoutImport
    }
    '/_defaultLayout/travel': {
      id: '/_defaultLayout/travel'
      path: '/travel'
      fullPath: '/travel'
      preLoaderRoute: typeof DefaultLayoutTravelImport
      parentRoute: typeof DefaultLayoutImport
    }
    '/_defaultLayout/': {
      id: '/_defaultLayout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DefaultLayoutIndexImport
      parentRoute: typeof DefaultLayoutImport
    }
    '/_defaultLayout/auth/login': {
      id: '/_defaultLayout/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof DefaultLayoutAuthLoginImport
      parentRoute: typeof DefaultLayoutImport
    }
    '/_defaultLayout/auth/signup': {
      id: '/_defaultLayout/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof DefaultLayoutAuthSignupImport
      parentRoute: typeof DefaultLayoutImport
    }
  }
}

// Create and export the route tree

interface DefaultLayoutRouteChildren {
  DefaultLayoutBlogRoute: typeof DefaultLayoutBlogRoute
  DefaultLayoutInvestmentRoute: typeof DefaultLayoutInvestmentRoute
  DefaultLayoutLedgerRoute: typeof DefaultLayoutLedgerRoute
  DefaultLayoutTravelRoute: typeof DefaultLayoutTravelRoute
  DefaultLayoutIndexRoute: typeof DefaultLayoutIndexRoute
  DefaultLayoutAuthLoginRoute: typeof DefaultLayoutAuthLoginRoute
  DefaultLayoutAuthSignupRoute: typeof DefaultLayoutAuthSignupRoute
}

const DefaultLayoutRouteChildren: DefaultLayoutRouteChildren = {
  DefaultLayoutBlogRoute: DefaultLayoutBlogRoute,
  DefaultLayoutInvestmentRoute: DefaultLayoutInvestmentRoute,
  DefaultLayoutLedgerRoute: DefaultLayoutLedgerRoute,
  DefaultLayoutTravelRoute: DefaultLayoutTravelRoute,
  DefaultLayoutIndexRoute: DefaultLayoutIndexRoute,
  DefaultLayoutAuthLoginRoute: DefaultLayoutAuthLoginRoute,
  DefaultLayoutAuthSignupRoute: DefaultLayoutAuthSignupRoute,
}

const DefaultLayoutRouteWithChildren = DefaultLayoutRoute._addFileChildren(
  DefaultLayoutRouteChildren,
)

export interface FileRoutesByFullPath {
  '': typeof DefaultLayoutRouteWithChildren
  '/blog': typeof DefaultLayoutBlogRoute
  '/investment': typeof DefaultLayoutInvestmentRoute
  '/ledger': typeof DefaultLayoutLedgerRoute
  '/travel': typeof DefaultLayoutTravelRoute
  '/': typeof DefaultLayoutIndexRoute
  '/auth/login': typeof DefaultLayoutAuthLoginRoute
  '/auth/signup': typeof DefaultLayoutAuthSignupRoute
}

export interface FileRoutesByTo {
  '/blog': typeof DefaultLayoutBlogRoute
  '/investment': typeof DefaultLayoutInvestmentRoute
  '/ledger': typeof DefaultLayoutLedgerRoute
  '/travel': typeof DefaultLayoutTravelRoute
  '/': typeof DefaultLayoutIndexRoute
  '/auth/login': typeof DefaultLayoutAuthLoginRoute
  '/auth/signup': typeof DefaultLayoutAuthSignupRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_defaultLayout': typeof DefaultLayoutRouteWithChildren
  '/_defaultLayout/blog': typeof DefaultLayoutBlogRoute
  '/_defaultLayout/investment': typeof DefaultLayoutInvestmentRoute
  '/_defaultLayout/ledger': typeof DefaultLayoutLedgerRoute
  '/_defaultLayout/travel': typeof DefaultLayoutTravelRoute
  '/_defaultLayout/': typeof DefaultLayoutIndexRoute
  '/_defaultLayout/auth/login': typeof DefaultLayoutAuthLoginRoute
  '/_defaultLayout/auth/signup': typeof DefaultLayoutAuthSignupRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/blog'
    | '/investment'
    | '/ledger'
    | '/travel'
    | '/'
    | '/auth/login'
    | '/auth/signup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/blog'
    | '/investment'
    | '/ledger'
    | '/travel'
    | '/'
    | '/auth/login'
    | '/auth/signup'
  id:
    | '__root__'
    | '/_defaultLayout'
    | '/_defaultLayout/blog'
    | '/_defaultLayout/investment'
    | '/_defaultLayout/ledger'
    | '/_defaultLayout/travel'
    | '/_defaultLayout/'
    | '/_defaultLayout/auth/login'
    | '/_defaultLayout/auth/signup'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  DefaultLayoutRoute: typeof DefaultLayoutRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  DefaultLayoutRoute: DefaultLayoutRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.jsx",
      "children": [
        "/_defaultLayout"
      ]
    },
    "/_defaultLayout": {
      "filePath": "_defaultLayout.jsx",
      "children": [
        "/_defaultLayout/blog",
        "/_defaultLayout/investment",
        "/_defaultLayout/ledger",
        "/_defaultLayout/travel",
        "/_defaultLayout/",
        "/_defaultLayout/auth/login",
        "/_defaultLayout/auth/signup"
      ]
    },
    "/_defaultLayout/blog": {
      "filePath": "_defaultLayout/blog.jsx",
      "parent": "/_defaultLayout"
    },
    "/_defaultLayout/investment": {
      "filePath": "_defaultLayout/investment.jsx",
      "parent": "/_defaultLayout"
    },
    "/_defaultLayout/ledger": {
      "filePath": "_defaultLayout/ledger.jsx",
      "parent": "/_defaultLayout"
    },
    "/_defaultLayout/travel": {
      "filePath": "_defaultLayout/travel.jsx",
      "parent": "/_defaultLayout"
    },
    "/_defaultLayout/": {
      "filePath": "_defaultLayout/index.jsx",
      "parent": "/_defaultLayout"
    },
    "/_defaultLayout/auth/login": {
      "filePath": "_defaultLayout/auth/login.jsx",
      "parent": "/_defaultLayout"
    },
    "/_defaultLayout/auth/signup": {
      "filePath": "_defaultLayout/auth/signup.jsx",
      "parent": "/_defaultLayout"
    }
  }
}
ROUTE_MANIFEST_END */
